version: "3.9"

services:
  backend:
    build: .
    volumes:
      - .:/app
    container_name: expense_tracker_backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - expense_network
    restart: always

  celery:
    build: .
    container_name: expense_worker
    command: celery -A backend worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - expense_network
    restart: always

  db:
    image: postgres:16
    container_name: expense_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - expense_network

  redis:
    image: redis:7
    container_name: expense_redis
    ports:
      - "6379:6379"
    networks:
      - expense_network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: expense_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - expense_network
    restart: always

networks:
  expense_network:
    driver: bridge

volumes:
  postgres_data:
