apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: expense_namespace
spec:
  type: ClusterIP #Local => Internal Access
  # type: LoadBalancer #Public Access
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
