kind: Secret
apiVersion: v1
metadata:
  name: expense_secrets
  namespace: expense_namespace
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: SECRET KEY
  DEBUG: "True"
  ALLOWED_HOSTS: 127.0.0.1,localhost,backend

  # Postgres
  POSTGRES_DB: enter_db_name
  POSTGRES_USER: enter_user_name
  POSTGRES_PASSWORD: enter_db_password
  POSTGRES_HOST: enter_host_name
  POSTGRES_PORT: enter_port_no.

  # Redis
  REDIS_HOST: enter_host
  REDIS_PORT: enter_port

  # Celery
  CELERY_BROKER_URL: enter_broker_url
  CELERY_RESULT_BACKEND: enter_backend_url

  # AI
  AI_API_KEY: enter_api_key
